// Solid State — ClawHub indexed listings (LIVE), generated 2026-05-29 by drafts/clawhub-candidates/generate.py
// Third-party skills indexed from ClawHub for discovery. We do NOT mirror code.
//   provenance "indexed" = ClawHub-listed + ClawHub-scanned, NOT Solid-State-audited.
//   license = ClawHub publisher-declared (not LICENSE-file-verified); null -> "unknown".
//   stats.installs = ClawHub installsAllTime (real telemetry). Reuse per ClawHub public-catalog policy.
// Held entries (gamed download counts / ToS or capability concerns) are intentionally excluded;
// see drafts/clawhub-candidates for the full top-50 review.

import type { Skill } from "./types"

export const clawhubListings: Skill[] = [
  {
    id: "clawhub-self-improving-agent",
    name: "Self-Improving Agent",
    slug: "clawhub-self-improving-agent",
    kind: "listing",
    description: "Captures learnings, errors, and corrections to enable continuous improvement of the agent.",
    longDescription:
      "Captures learnings, errors, and corrections to enable continuous improvement of the agent. Indexed from ClawHub for discovery; install via OpenClaw. Solid State has not audited this skill.",
    author: "pskoett",
    version: "3.0.21",
    platforms: ["openclaw", "generic"],
    categories: ["AI"],
    installCommand: "openclaw skills install self-improving-agent",
    docsUrl: "https://clawhub.ai/pskoett/self-improving-agent",
    license: "MIT-0",
    status: "stable",
    provenance: "indexed",
    featured: false,
    tags: ["clawhub", "openclaw", "ai"],
    createdAt: "2026-05-29",
    stats: { installs: 18286, stars: 3808, fetchedAt: "2026-06-22" },
    source: "clawhub:pskoett/self-improving-agent",
    external: true,
  },
  {
    id: "clawhub-skill-vetter",
    name: "Skill Vetter",
    slug: "clawhub-skill-vetter",
    kind: "listing",
    description: "Security-first skill vetting for AI agents. Checks red flags, permission scope, suspicious patterns before install.",
    longDescription:
      "Security-first skill vetting for AI agents. Checks red flags, permission scope, suspicious patterns before install. Indexed from ClawHub for discovery; install via OpenClaw. Solid State has not audited this skill.",
    author: "spclaudehome",
    version: "1.0.0",
    platforms: ["openclaw", "generic"],
    categories: ["Security"],
    installCommand: "openclaw skills install skill-vetter",
    docsUrl: "https://clawhub.ai/spclaudehome/skill-vetter",
    license: "undeclared",
    status: "stable",
    provenance: "indexed",
    featured: false,
    tags: ["clawhub", "openclaw", "security"],
    createdAt: "2026-05-29",
    stats: { installs: 11936, stars: 1243, fetchedAt: "2026-06-29" },
    source: "clawhub:spclaudehome/skill-vetter",
    external: true,
  },
  {
    id: "clawhub-self-improving",
    name: "Self-Improving + Proactive Agent",
    slug: "clawhub-self-improving",
    kind: "listing",
    description: "Self-reflection, self-criticism, self-learning and self-organizing memory for agents.",
    longDescription:
      "Self-reflection, self-criticism, self-learning and self-organizing memory for agents. Indexed from ClawHub for discovery; install via OpenClaw. Solid State has not audited this skill.",
    author: "ivangdavila",
    version: "1.2.16",
    platforms: ["openclaw", "generic"],
    categories: ["AI"],
    installCommand: "openclaw skills install self-improving",
    docsUrl: "https://clawhub.ai/ivangdavila/self-improving",
    license: "MIT-0",
    status: "stable",
    provenance: "indexed",
    featured: false,
    tags: ["clawhub", "openclaw", "ai"],
    createdAt: "2026-05-29",
    stats: { installs: 7224, stars: 1235, fetchedAt: "2026-06-29" },
    source: "clawhub:ivangdavila/self-improving",
    external: true,
  },
  {
    id: "clawhub-ontology",
    name: "ontology",
    slug: "clawhub-ontology",
    kind: "listing",
    description: "Typed knowledge graph for structured agent memory and composable skills.",
    longDescription:
      "Typed knowledge graph for structured agent memory and composable skills. Indexed from ClawHub for discovery; install via OpenClaw. Solid State has not audited this skill.",
    author: "oswalpalash",
    version: "1.0.4",
    platforms: ["openclaw", "generic"],
    categories: ["AI"],
    installCommand: "openclaw skills install ontology",
    docsUrl: "https://clawhub.ai/oswalpalash/ontology",
    license: "MIT-0",
    status: "stable",
    provenance: "indexed",
    featured: false,
    tags: ["clawhub", "openclaw", "ai"],
    createdAt: "2026-05-29",
    stats: { installs: 7213, stars: 648, fetchedAt: "2026-06-29" },
    source: "clawhub:oswalpalash/ontology",
    external: true,
  },
  {
    id: "clawhub-github",
    name: "Github",
    slug: "clawhub-github",
    kind: "listing",
    description: "Interact with GitHub using the gh CLI: issues, PRs, CI runs, and gh api queries.",
    longDescription:
      "Interact with GitHub using the gh CLI: issues, PRs, CI runs, and gh api queries. Indexed from ClawHub for discovery; install via OpenClaw. Solid State has not audited this skill.",
    author: "steipete",
    version: "1.0.0",
    platforms: ["openclaw", "generic"],
    categories: ["DevOps"],
    installCommand: "openclaw skills install github",
    docsUrl: "https://clawhub.ai/steipete/github",
    license: "undeclared",
    status: "stable",
    provenance: "indexed",
    featured: false,
    tags: ["clawhub", "openclaw", "devops"],
    createdAt: "2026-05-29",
    stats: { installs: 7603, stars: 639, fetchedAt: "2026-06-22" },
    source: "clawhub:steipete/github",
    external: true,
  },
  {
    id: "clawhub-gog",
    name: "Gog",
    slug: "clawhub-gog",
    kind: "listing",
    description: "Google Workspace CLI for Gmail, Calendar, Drive, Contacts, Sheets, and Docs.",
    longDescription:
      "Google Workspace CLI for Gmail, Calendar, Drive, Contacts, Sheets, and Docs. Indexed from ClawHub for discovery; install via OpenClaw. Solid State has not audited this skill.",
    author: "steipete",
    version: "1.0.0",
    platforms: ["openclaw", "generic"],
    categories: ["Productivity"],
    installCommand: "openclaw skills install gog",
    docsUrl: "https://clawhub.ai/steipete/gog",
    license: "undeclared",
    status: "stable",
    provenance: "indexed",
    featured: false,
    tags: ["clawhub", "openclaw", "productivity"],
    createdAt: "2026-05-29",
    stats: { installs: 5442, stars: 933, fetchedAt: "2026-06-29" },
    source: "clawhub:steipete/gog",
    external: true,
  },
  {
    id: "clawhub-proactive-agent",
    name: "Proactive Agent",
    slug: "clawhub-proactive-agent",
    kind: "listing",
    description: "Turns agents into proactive partners. WAL protocol, working buffer, autonomous crons.",
    longDescription:
      "Turns agents into proactive partners. WAL protocol, working buffer, autonomous crons. Indexed from ClawHub for discovery; install via OpenClaw. Solid State has not audited this skill.",
    author: "halthelobster",
    version: "3.1.0",
    platforms: ["openclaw", "generic"],
    categories: ["AI"],
    installCommand: "openclaw skills install proactive-agent",
    docsUrl: "https://clawhub.ai/halthelobster/proactive-agent",
    license: "undeclared",
    status: "stable",
    provenance: "indexed",
    featured: false,
    tags: ["clawhub", "openclaw", "ai"],
    createdAt: "2026-05-29",
    stats: { installs: 7141, stars: 814, fetchedAt: "2026-06-29" },
    source: "clawhub:halthelobster/proactive-agent",
    external: true,
  },
  {
    id: "clawhub-weather",
    name: "Weather",
    slug: "clawhub-weather",
    kind: "listing",
    description: "Get current weather and forecasts (no API key required).",
    longDescription:
      "Get current weather and forecasts (no API key required). Indexed from ClawHub for discovery; install via OpenClaw. Solid State has not audited this skill.",
    author: "steipete",
    version: "1.0.0",
    platforms: ["openclaw", "generic"],
    categories: ["Utilities"],
    installCommand: "openclaw skills install weather",
    docsUrl: "https://clawhub.ai/steipete/weather",
    license: "undeclared",
    status: "stable",
    provenance: "indexed",
    featured: false,
    tags: ["clawhub", "openclaw", "utilities"],
    createdAt: "2026-05-29",
    stats: { installs: 6464, stars: 421, fetchedAt: "2026-06-29" },
    source: "clawhub:steipete/weather",
    external: true,
  },
  {
    id: "clawhub-multi-search-engine",
    name: "Multi Search Engine",
    slug: "clawhub-multi-search-engine",
    kind: "listing",
    description: "16-engine search (7 CN + 9 global) with operators, time filters, privacy engines.",
    longDescription:
      "16-engine search (7 CN + 9 global) with operators, time filters, privacy engines. Indexed from ClawHub for discovery; install via OpenClaw. Solid State has not audited this skill.",
    author: "gpyangyoujun",
    version: "2.1.3",
    platforms: ["openclaw", "generic"],
    categories: ["Research"],
    installCommand: "openclaw skills install multi-search-engine",
    docsUrl: "https://clawhub.ai/gpyangyoujun/multi-search-engine",
    license: "MIT-0",
    status: "stable",
    provenance: "indexed",
    featured: false,
    tags: ["clawhub", "openclaw", "research"],
    createdAt: "2026-05-29",
    stats: { installs: 5444, stars: 739, fetchedAt: "2026-06-29" },
    source: "clawhub:gpyangyoujun/multi-search-engine",
    external: true,
  },
  {
    id: "clawhub-humanizer",
    name: "Humanizer",
    slug: "clawhub-humanizer",
    kind: "listing",
    description: "Remove signs of AI-generated writing based on Wikipedia's Signs of AI Writing guide.",
    longDescription:
      "Remove signs of AI-generated writing based on Wikipedia's Signs of AI Writing guide. Indexed from ClawHub for discovery; install via OpenClaw. Solid State has not audited this skill.",
    author: "biostartechnology",
    version: "1.0.0",
    platforms: ["openclaw", "generic"],
    categories: ["Writing"],
    installCommand: "openclaw skills install humanizer",
    docsUrl: "https://clawhub.ai/biostartechnology/humanizer",
    license: "undeclared",
    status: "stable",
    provenance: "indexed",
    featured: false,
    tags: ["clawhub", "openclaw", "writing"],
    createdAt: "2026-05-29",
    stats: { installs: 4637, stars: 677, fetchedAt: "2026-06-22" },
    source: "clawhub:biostartechnology/humanizer",
    external: true,
  },
  {
    id: "clawhub-agent-browser-clawdbot",
    name: "Agent Browser",
    slug: "clawhub-agent-browser-clawdbot",
    kind: "listing",
    description: "Headless browser automation CLI for agents with accessibility-tree snapshots and ref-based selection.",
    longDescription:
      "Headless browser automation CLI for agents with accessibility-tree snapshots and ref-based selection. Indexed from ClawHub for discovery; install via OpenClaw. Solid State has not audited this skill.",
    author: "matrixy",
    version: "0.1.0",
    platforms: ["openclaw", "generic"],
    categories: ["Automation"],
    installCommand: "openclaw skills install agent-browser-clawdbot",
    docsUrl: "https://clawhub.ai/matrixy/agent-browser-clawdbot",
    license: "undeclared",
    status: "beta",
    provenance: "indexed",
    featured: false,
    tags: ["clawhub", "openclaw", "automation"],
    createdAt: "2026-05-29",
    stats: { installs: 1348, stars: 434, fetchedAt: "2026-06-29" },
    source: "clawhub:matrixy/agent-browser-clawdbot",
    external: true,
  },
  {
    id: "clawhub-nano-pdf",
    name: "Nano Pdf",
    slug: "clawhub-nano-pdf",
    kind: "listing",
    description: "Edit PDFs with natural-language instructions using the nano-pdf CLI.",
    longDescription:
      "Edit PDFs with natural-language instructions using the nano-pdf CLI. Indexed from ClawHub for discovery; install via OpenClaw. Solid State has not audited this skill.",
    author: "steipete",
    version: "1.0.0",
    platforms: ["openclaw", "generic"],
    categories: ["Productivity"],
    installCommand: "openclaw skills install nano-pdf",
    docsUrl: "https://clawhub.ai/steipete/nano-pdf",
    license: "undeclared",
    status: "stable",
    provenance: "indexed",
    featured: false,
    tags: ["clawhub", "openclaw", "productivity"],
    createdAt: "2026-05-29",
    stats: { installs: 4345, stars: 263, fetchedAt: "2026-06-29" },
    source: "clawhub:steipete/nano-pdf",
    external: true,
  },
  {
    id: "clawhub-nano-banana-pro",
    name: "Nano Banana Pro",
    slug: "clawhub-nano-banana-pro",
    kind: "listing",
    description: "Generate/edit images with Nano Banana Pro (Gemini 3 Pro Image). Text-to-image and image-to-image.",
    longDescription:
      "Generate/edit images with Nano Banana Pro (Gemini 3 Pro Image). Text-to-image and image-to-image. Indexed from ClawHub for discovery; install via OpenClaw. Solid State has not audited this skill.",
    author: "steipete",
    version: "1.0.1",
    platforms: ["openclaw", "generic"],
    categories: ["Creative"],
    installCommand: "openclaw skills install nano-banana-pro",
    docsUrl: "https://clawhub.ai/steipete/nano-banana-pro",
    license: "undeclared",
    status: "stable",
    provenance: "indexed",
    featured: false,
    tags: ["clawhub", "openclaw", "creative"],
    createdAt: "2026-05-29",
    stats: { installs: 3086, stars: 410, fetchedAt: "2026-06-29" },
    source: "clawhub:steipete/nano-banana-pro",
    external: true,
  },
  {
    id: "clawhub-obsidian",
    name: "Obsidian",
    slug: "clawhub-obsidian",
    kind: "listing",
    description: "Work with Obsidian vaults (plain Markdown notes) and automate via obsidian-cli.",
    longDescription:
      "Work with Obsidian vaults (plain Markdown notes) and automate via obsidian-cli. Indexed from ClawHub for discovery; install via OpenClaw. Solid State has not audited this skill.",
    author: "steipete",
    version: "1.0.0",
    platforms: ["openclaw", "generic"],
    categories: ["Productivity"],
    installCommand: "openclaw skills install obsidian",
    docsUrl: "https://clawhub.ai/steipete/obsidian",
    license: "undeclared",
    status: "stable",
    provenance: "indexed",
    featured: false,
    tags: ["clawhub", "openclaw", "productivity"],
    createdAt: "2026-05-29",
    stats: { installs: 4101, stars: 431, fetchedAt: "2026-06-22" },
    source: "clawhub:steipete/obsidian",
    external: true,
  },
  {
    id: "clawhub-openclaw-tavily-search",
    name: "Tavily Search (CN)",
    slug: "clawhub-openclaw-tavily-search",
    kind: "listing",
    description: "Web search via Tavily API (alternative to Brave) with brave-like structured output.",
    longDescription:
      "Web search via Tavily API (alternative to Brave) with brave-like structured output. Indexed from ClawHub for discovery; install via OpenClaw. Solid State has not audited this skill.",
    author: "jacky1n7",
    version: "0.1.0",
    platforms: ["openclaw", "generic"],
    categories: ["Research"],
    installCommand: "openclaw skills install openclaw-tavily-search",
    docsUrl: "https://clawhub.ai/jacky1n7/openclaw-tavily-search",
    license: "undeclared",
    status: "beta",
    provenance: "indexed",
    featured: false,
    tags: ["clawhub", "openclaw", "research"],
    createdAt: "2026-05-29",
    stats: { installs: 3414, stars: 266, fetchedAt: "2026-06-29" },
    source: "clawhub:jacky1n7/openclaw-tavily-search",
    external: true,
  },
  {
    id: "clawhub-auto-updater",
    name: "Auto-Updater Skill",
    slug: "clawhub-auto-updater",
    kind: "listing",
    description: "Automatically update Clawdbot and all installed skills once daily via cron.",
    longDescription:
      "Automatically update Clawdbot and all installed skills once daily via cron. Indexed from ClawHub for discovery; install via OpenClaw. Solid State has not audited this skill.",
    author: "maximeprades",
    version: "1.0.0",
    platforms: ["openclaw", "generic"],
    categories: ["DevOps"],
    installCommand: "openclaw skills install auto-updater",
    docsUrl: "https://clawhub.ai/maximeprades/auto-updater",
    license: "undeclared",
    status: "stable",
    provenance: "indexed",
    featured: false,
    tags: ["clawhub", "openclaw", "devops"],
    createdAt: "2026-05-29",
    stats: { installs: 1507, stars: 427, fetchedAt: "2026-06-15" },
    source: "clawhub:maximeprades/auto-updater",
    external: true,
  },
  {
    id: "clawhub-notion",
    name: "Notion",
    slug: "clawhub-notion",
    kind: "listing",
    description: "Notion API for creating and managing pages, databases, and blocks.",
    longDescription:
      "Notion API for creating and managing pages, databases, and blocks. Indexed from ClawHub for discovery; install via OpenClaw. Solid State has not audited this skill.",
    author: "steipete",
    version: "1.0.0",
    platforms: ["openclaw", "generic"],
    categories: ["Productivity"],
    installCommand: "openclaw skills install notion",
    docsUrl: "https://clawhub.ai/steipete/notion",
    license: "undeclared",
    status: "stable",
    provenance: "indexed",
    featured: false,
    tags: ["clawhub", "openclaw", "productivity"],
    createdAt: "2026-05-29",
    stats: { installs: 3194, stars: 262, fetchedAt: "2026-06-29" },
    source: "clawhub:steipete/notion",
    external: true,
  },
  {
    id: "clawhub-baidu-search",
    name: "Baidu web search",
    slug: "clawhub-baidu-search",
    kind: "listing",
    description: "Search the web using Baidu AI Search Engine (BDSE).",
    longDescription:
      "Search the web using Baidu AI Search Engine (BDSE). Indexed from ClawHub for discovery; install via OpenClaw. Solid State has not audited this skill.",
    author: "ide-rea",
    version: "1.1.4",
    platforms: ["openclaw", "generic"],
    categories: ["Research"],
    installCommand: "openclaw skills install baidu-search",
    docsUrl: "https://clawhub.ai/ide-rea/baidu-search",
    license: "MIT-0",
    status: "stable",
    provenance: "indexed",
    featured: false,
    tags: ["clawhub", "openclaw", "research"],
    createdAt: "2026-05-29",
    stats: { installs: 969, stars: 216, fetchedAt: "2026-06-15" },
    source: "clawhub:ide-rea/baidu-search",
    external: true,
  },
  {
    id: "clawhub-skill-creator",
    name: "Skill Creator",
    slug: "clawhub-skill-creator",
    kind: "listing",
    description: "Guide for creating effective skills that extend an agent with workflows or tool integrations.",
    longDescription:
      "Guide for creating effective skills that extend an agent with workflows or tool integrations. Indexed from ClawHub for discovery; install via OpenClaw. Solid State has not audited this skill.",
    author: "chindden",
    version: "0.1.0",
    platforms: ["openclaw", "generic"],
    categories: ["AI"],
    installCommand: "openclaw skills install skill-creator",
    docsUrl: "https://clawhub.ai/chindden/skill-creator",
    license: "undeclared",
    status: "beta",
    provenance: "indexed",
    featured: false,
    tags: ["clawhub", "openclaw", "ai"],
    createdAt: "2026-05-29",
    stats: { installs: 3388, stars: 325, fetchedAt: "2026-06-29" },
    source: "clawhub:chindden/skill-creator",
    external: true,
  },
  {
    id: "clawhub-sonoscli",
    name: "Sonoscli",
    slug: "clawhub-sonoscli",
    kind: "listing",
    description: "Control Sonos speakers (discover/status/play/volume/group).",
    longDescription:
      "Control Sonos speakers (discover/status/play/volume/group). Indexed from ClawHub for discovery; install via OpenClaw. Solid State has not audited this skill.",
    author: "steipete",
    version: "1.0.0",
    platforms: ["openclaw", "generic"],
    categories: ["Utilities"],
    installCommand: "openclaw skills install sonoscli",
    docsUrl: "https://clawhub.ai/steipete/sonoscli",
    license: "undeclared",
    status: "stable",
    provenance: "indexed",
    featured: false,
    tags: ["clawhub", "openclaw", "utilities"],
    createdAt: "2026-05-29",
    stats: { installs: 2797, stars: 56, fetchedAt: "2026-06-29" },
    source: "clawhub:steipete/sonoscli",
    external: true,
  },
  {
    id: "clawhub-openai-whisper",
    name: "Openai Whisper",
    slug: "clawhub-openai-whisper",
    kind: "listing",
    description: "Local speech-to-text with the Whisper CLI (no API key).",
    longDescription:
      "Local speech-to-text with the Whisper CLI (no API key). Indexed from ClawHub for discovery; install via OpenClaw. Solid State has not audited this skill.",
    author: "steipete",
    version: "1.0.0",
    platforms: ["openclaw", "generic"],
    categories: ["Utilities"],
    installCommand: "openclaw skills install openai-whisper",
    docsUrl: "https://clawhub.ai/steipete/openai-whisper",
    license: "undeclared",
    status: "stable",
    provenance: "indexed",
    featured: false,
    tags: ["clawhub", "openclaw", "utilities"],
    createdAt: "2026-05-29",
    stats: { installs: 2958, stars: 329, fetchedAt: "2026-06-29" },
    source: "clawhub:steipete/openai-whisper",
    external: true,
  },
  {
    id: "clawhub-api-gateway",
    name: "API Gateway",
    slug: "clawhub-api-gateway",
    kind: "listing",
    description: "Connect to external services through Maton-managed API routes.",
    longDescription:
      "Connect to external services through Maton-managed API routes. Indexed from ClawHub for discovery; install via OpenClaw. Solid State has not audited this skill.",
    author: "byungkyu",
    version: "1.0.124",
    platforms: ["openclaw", "generic"],
    categories: ["DevOps"],
    installCommand: "openclaw skills install api-gateway",
    docsUrl: "https://clawhub.ai/byungkyu/api-gateway",
    license: "MIT-0",
    status: "stable",
    provenance: "indexed",
    featured: false,
    tags: ["clawhub", "openclaw", "devops"],
    createdAt: "2026-05-29",
    stats: { installs: 2493, stars: 390, fetchedAt: "2026-06-22" },
    source: "clawhub:byungkyu/api-gateway",
    external: true,
  },
  {
    id: "clawhub-word-docx",
    name: "Word / DOCX",
    slug: "clawhub-word-docx",
    kind: "listing",
    description: "Create, inspect, and edit Word/DOCX files with styles, numbering, tracked changes, tables.",
    longDescription:
      "Create, inspect, and edit Word/DOCX files with styles, numbering, tracked changes, tables. Indexed from ClawHub for discovery; install via OpenClaw. Solid State has not audited this skill.",
    author: "ivangdavila",
    version: "1.0.2",
    platforms: ["openclaw", "generic"],
    categories: ["Productivity"],
    installCommand: "openclaw skills install word-docx",
    docsUrl: "https://clawhub.ai/ivangdavila/word-docx",
    license: "MIT-0",
    status: "stable",
    provenance: "indexed",
    featured: false,
    tags: ["clawhub", "openclaw", "productivity"],
    createdAt: "2026-05-29",
    stats: { installs: 2727, stars: 347, fetchedAt: "2026-06-29" },
    source: "clawhub:ivangdavila/word-docx",
    external: true,
  },
  {
    id: "clawhub-automation-workflows",
    name: "Automation Workflows",
    slug: "clawhub-automation-workflows",
    kind: "listing",
    description: "Design and implement no-code automation workflows (Zapier, Make, n8n) for solopreneurs.",
    longDescription:
      "Design and implement no-code automation workflows (Zapier, Make, n8n) for solopreneurs. Indexed from ClawHub for discovery; install via OpenClaw. Solid State has not audited this skill.",
    author: "jk-0001",
    version: "0.1.0",
    platforms: ["openclaw", "generic"],
    categories: ["Automation"],
    installCommand: "openclaw skills install automation-workflows",
    docsUrl: "https://clawhub.ai/jk-0001/automation-workflows",
    license: "undeclared",
    status: "beta",
    provenance: "indexed",
    featured: false,
    tags: ["clawhub", "openclaw", "automation"],
    createdAt: "2026-05-29",
    stats: { installs: 1100, stars: 305, fetchedAt: "2026-06-15" },
    source: "clawhub:jk-0001/automation-workflows",
    external: true,
  },
  {
    id: "clawhub-excel-xlsx",
    name: "Excel / XLSX",
    slug: "clawhub-excel-xlsx",
    kind: "listing",
    description: "Create, inspect, and edit Excel/XLSX files with formulas, dates, formatting, recalculation.",
    longDescription:
      "Create, inspect, and edit Excel/XLSX files with formulas, dates, formatting, recalculation. Indexed from ClawHub for discovery; install via OpenClaw. Solid State has not audited this skill.",
    author: "ivangdavila",
    version: "1.0.2",
    platforms: ["openclaw", "generic"],
    categories: ["Productivity"],
    installCommand: "openclaw skills install excel-xlsx",
    docsUrl: "https://clawhub.ai/ivangdavila/excel-xlsx",
    license: "MIT-0",
    status: "stable",
    provenance: "indexed",
    featured: false,
    tags: ["clawhub", "openclaw", "productivity"],
    createdAt: "2026-05-29",
    stats: { installs: 2673, stars: 284, fetchedAt: "2026-06-22" },
    source: "clawhub:ivangdavila/excel-xlsx",
    external: true,
  },
  {
    id: "clawhub-mcporter",
    name: "Mcporter",
    slug: "clawhub-mcporter",
    kind: "listing",
    description: "Use the mcporter CLI to list, configure, auth, and call MCP servers/tools directly.",
    longDescription:
      "Use the mcporter CLI to list, configure, auth, and call MCP servers/tools directly. Indexed from ClawHub for discovery; install via OpenClaw. Solid State has not audited this skill.",
    author: "steipete",
    version: "1.0.0",
    platforms: ["openclaw", "generic"],
    categories: ["MCP", "DevOps"],
    installCommand: "openclaw skills install mcporter",
    docsUrl: "https://clawhub.ai/steipete/mcporter",
    license: "undeclared",
    status: "stable",
    provenance: "indexed",
    featured: false,
    tags: ["clawhub", "openclaw", "devops"],
    createdAt: "2026-05-29",
    stats: { installs: 2171, stars: 195, fetchedAt: "2026-06-22" },
    source: "clawhub:steipete/mcporter",
    external: true,
  },
  {
    id: "clawhub-elite-longterm-memory",
    name: "Elite Longterm Memory",
    slug: "clawhub-elite-longterm-memory",
    kind: "listing",
    description: "Agent memory system: WAL protocol + vector search + git-notes + cloud backup.",
    longDescription:
      "Agent memory system: WAL protocol + vector search + git-notes + cloud backup. Indexed from ClawHub for discovery; install via OpenClaw. Solid State has not audited this skill.",
    author: "nextfrontierbuilds",
    version: "1.2.3",
    platforms: ["openclaw", "generic"],
    categories: ["AI"],
    installCommand: "openclaw skills install elite-longterm-memory",
    docsUrl: "https://clawhub.ai/nextfrontierbuilds/elite-longterm-memory",
    license: "undeclared",
    status: "stable",
    provenance: "indexed",
    featured: false,
    tags: ["clawhub", "openclaw", "ai"],
    createdAt: "2026-05-29",
    stats: { installs: 2241, stars: 225, fetchedAt: "2026-06-29" },
    source: "clawhub:nextfrontierbuilds/elite-longterm-memory",
    external: true,
  },
  {
    id: "clawhub-brave-search",
    name: "Brave Search",
    slug: "clawhub-brave-search",
    kind: "listing",
    description: "Web search and content extraction via Brave Search API. Lightweight, no browser.",
    longDescription:
      "Web search and content extraction via Brave Search API. Lightweight, no browser. Indexed from ClawHub for discovery; install via OpenClaw. Solid State has not audited this skill.",
    author: "steipete",
    version: "1.0.1",
    platforms: ["openclaw", "generic"],
    categories: ["Research"],
    installCommand: "openclaw skills install brave-search",
    docsUrl: "https://clawhub.ai/steipete/brave-search",
    license: "undeclared",
    status: "stable",
    provenance: "indexed",
    featured: false,
    tags: ["clawhub", "openclaw", "research"],
    createdAt: "2026-05-29",
    stats: { installs: 2062, stars: 190, fetchedAt: "2026-06-29" },
    source: "clawhub:steipete/brave-search",
    external: true,
  },
  {
    id: "clawhub-desktop-control",
    name: "Desktop Control",
    slug: "clawhub-desktop-control",
    kind: "listing",
    description: "Advanced desktop automation with mouse, keyboard, and screen control.",
    longDescription:
      "Advanced desktop automation with mouse, keyboard, and screen control. Indexed from ClawHub for discovery; install via OpenClaw. Solid State has not audited this skill.",
    author: "matagul",
    version: "1.0.0",
    platforms: ["openclaw", "generic"],
    categories: ["Automation"],
    installCommand: "openclaw skills install desktop-control",
    docsUrl: "https://clawhub.ai/matagul/desktop-control",
    license: "undeclared",
    status: "stable",
    provenance: "indexed",
    featured: false,
    tags: ["clawhub", "openclaw", "automation"],
    createdAt: "2026-05-29",
    stats: { installs: 1855, stars: 371, fetchedAt: "2026-06-22" },
    source: "clawhub:matagul/desktop-control",
    external: true,
  },
  {
    id: "clawhub-stock-analysis",
    name: "Stock Analysis",
    slug: "clawhub-stock-analysis",
    kind: "listing",
    description: "Analyze stocks and crypto via Yahoo Finance: portfolios, watchlists, scoring, trend detection.",
    longDescription:
      "Analyze stocks and crypto via Yahoo Finance: portfolios, watchlists, scoring, trend detection. Indexed from ClawHub for discovery; install via OpenClaw. Solid State has not audited this skill.",
    author: "udiedrichsen",
    version: "6.2.0",
    platforms: ["openclaw", "generic"],
    categories: ["Finance"],
    installCommand: "openclaw skills install stock-analysis",
    docsUrl: "https://clawhub.ai/udiedrichsen/stock-analysis",
    license: "undeclared",
    status: "stable",
    provenance: "indexed",
    featured: false,
    tags: ["clawhub", "openclaw", "finance"],
    createdAt: "2026-05-29",
    stats: { installs: 2076, stars: 247, fetchedAt: "2026-06-29" },
    source: "clawhub:udiedrichsen/stock-analysis",
    external: true,
  },
  {
    id: "clawhub-youtube-watcher",
    name: "YouTube Watcher",
    slug: "clawhub-youtube-watcher",
    kind: "listing",
    description: "Fetch and read YouTube transcripts to summarize or answer questions about videos.",
    longDescription:
      "Fetch and read YouTube transcripts to summarize or answer questions about videos. Indexed from ClawHub for discovery; install via OpenClaw. Solid State has not audited this skill.",
    author: "michaelgathara",
    version: "1.0.0",
    platforms: ["openclaw", "generic"],
    categories: ["Research"],
    installCommand: "openclaw skills install youtube-watcher",
    docsUrl: "https://clawhub.ai/michaelgathara/youtube-watcher",
    license: "undeclared",
    status: "stable",
    provenance: "indexed",
    featured: false,
    tags: ["clawhub", "openclaw", "research"],
    createdAt: "2026-05-29",
    stats: { installs: 1647, stars: 333, fetchedAt: "2026-06-29" },
    source: "clawhub:michaelgathara/youtube-watcher",
    external: true,
  },
  {
    id: "clawhub-video-frames",
    name: "Video Frames",
    slug: "clawhub-video-frames",
    kind: "listing",
    description: "Extract frames or short clips from videos using ffmpeg.",
    longDescription:
      "Extract frames or short clips from videos using ffmpeg. Indexed from ClawHub for discovery; install via OpenClaw. Solid State has not audited this skill.",
    author: "steipete",
    version: "1.0.0",
    platforms: ["openclaw", "generic"],
    categories: ["Creative"],
    installCommand: "openclaw skills install video-frames",
    docsUrl: "https://clawhub.ai/steipete/video-frames",
    license: "undeclared",
    status: "stable",
    provenance: "indexed",
    featured: false,
    tags: ["clawhub", "openclaw", "creative"],
    createdAt: "2026-05-29",
    stats: { installs: 1604, stars: 131, fetchedAt: "2026-06-29" },
    source: "clawhub:steipete/video-frames",
    external: true,
  },
  {
    id: "clawhub-find-skills-skill",
    name: "Find Skills Skill",
    slug: "clawhub-find-skills-skill",
    kind: "listing",
    description: "Search and discover OpenClaw skills across ClawHub, directories, GitHub, and forums.",
    longDescription:
      "Search and discover OpenClaw skills across ClawHub, directories, GitHub, and forums. Indexed from ClawHub for discovery; install via OpenClaw. Solid State has not audited this skill.",
    author: "fangkelvin",
    version: "1.0.0",
    platforms: ["openclaw", "generic"],
    categories: ["AI"],
    installCommand: "openclaw skills install find-skills-skill",
    docsUrl: "https://clawhub.ai/fangkelvin/find-skills-skill",
    license: "undeclared",
    status: "stable",
    provenance: "indexed",
    featured: false,
    tags: ["clawhub", "openclaw", "ai"],
    createdAt: "2026-05-29",
    stats: { installs: 1721, stars: 141, fetchedAt: "2026-06-29" },
    source: "clawhub:fangkelvin/find-skills-skill",
    external: true,
  },
  {
    id: "clawhub-imap-smtp-email",
    name: "imap-smtp-email",
    slug: "clawhub-imap-smtp-email",
    kind: "listing",
    description: "Read and send email via IMAP/SMTP: unread, fetch, search, mark read, send with attachments.",
    longDescription:
      "Read and send email via IMAP/SMTP: unread, fetch, search, mark read, send with attachments. Indexed from ClawHub for discovery; install via OpenClaw. Solid State has not audited this skill.",
    author: "gzlicanyi",
    version: "0.0.15",
    platforms: ["openclaw", "generic"],
    categories: ["Productivity"],
    installCommand: "openclaw skills install imap-smtp-email",
    docsUrl: "https://clawhub.ai/gzlicanyi/imap-smtp-email",
    license: "MIT-0",
    status: "beta",
    provenance: "indexed",
    featured: false,
    tags: ["clawhub", "openclaw", "productivity"],
    createdAt: "2026-05-29",
    stats: { installs: 1530, stars: 105, fetchedAt: "2026-06-29" },
    source: "clawhub:gzlicanyi/imap-smtp-email",
    external: true,
  },
  {
    id: "clawhub-slack",
    name: "Slack",
    slug: "clawhub-slack",
    kind: "listing",
    description: "Control Slack from Clawdbot: react to messages, pin/unpin items in channels or DMs.",
    longDescription:
      "Control Slack from Clawdbot: react to messages, pin/unpin items in channels or DMs. Indexed from ClawHub for discovery; install via OpenClaw. Solid State has not audited this skill.",
    author: "steipete",
    version: "1.0.0",
    platforms: ["openclaw", "generic"],
    categories: ["Productivity"],
    installCommand: "openclaw skills install slack",
    docsUrl: "https://clawhub.ai/steipete/slack",
    license: "undeclared",
    status: "stable",
    provenance: "indexed",
    featured: false,
    tags: ["clawhub", "openclaw", "productivity"],
    createdAt: "2026-05-29",
    stats: { installs: 1487, stars: 159, fetchedAt: "2026-06-29" },
    source: "clawhub:steipete/slack",
    external: true,
  },
  {
    id: "clawhub-powerpoint-pptx",
    name: "Powerpoint / PPTX",
    slug: "clawhub-powerpoint-pptx",
    kind: "listing",
    description: "Create, inspect, and edit PowerPoint/PPTX decks with layouts, templates, notes, charts.",
    longDescription:
      "Create, inspect, and edit PowerPoint/PPTX decks with layouts, templates, notes, charts. Indexed from ClawHub for discovery; install via OpenClaw. Solid State has not audited this skill.",
    author: "ivangdavila",
    version: "1.0.1",
    platforms: ["openclaw", "generic"],
    categories: ["Productivity"],
    installCommand: "openclaw skills install powerpoint-pptx",
    docsUrl: "https://clawhub.ai/ivangdavila/powerpoint-pptx",
    license: "MIT-0",
    status: "stable",
    provenance: "indexed",
    featured: false,
    tags: ["clawhub", "openclaw", "productivity"],
    createdAt: "2026-05-29",
    stats: { installs: 1488, stars: 141, fetchedAt: "2026-06-29" },
    source: "clawhub:ivangdavila/powerpoint-pptx",
    external: true,
  },
  {
    id: "clawhub-browser-automation",
    name: "Browser Automation",
    slug: "clawhub-browser-automation",
    kind: "listing",
    description: "Automate browser interactions via natural-language CLI: navigate, extract, screenshot, fill forms.",
    longDescription:
      "Automate browser interactions via natural-language CLI: navigate, extract, screenshot, fill forms. Indexed from ClawHub for discovery; install via OpenClaw. Solid State has not audited this skill.",
    author: "peytoncasper",
    version: "1.0.1",
    platforms: ["openclaw", "generic"],
    categories: ["Automation"],
    installCommand: "openclaw skills install browser-automation",
    docsUrl: "https://clawhub.ai/peytoncasper/browser-automation",
    license: "undeclared",
    status: "stable",
    provenance: "indexed",
    featured: false,
    tags: ["clawhub", "openclaw", "automation"],
    createdAt: "2026-05-29",
    stats: { installs: 542, stars: 62, fetchedAt: "2026-06-15" },
    source: "clawhub:peytoncasper/browser-automation",
    external: true,
  },
  {
    id: "clawhub-himalaya",
    name: "Himalaya",
    slug: "clawhub-himalaya",
    kind: "listing",
    description: "CLI to manage email via IMAP/SMTP: list, read, write, reply, forward, search, organize.",
    longDescription:
      "CLI to manage email via IMAP/SMTP: list, read, write, reply, forward, search, organize. Indexed from ClawHub for discovery; install via OpenClaw. Solid State has not audited this skill.",
    author: "lamelas",
    version: "1.0.0",
    platforms: ["openclaw", "generic"],
    categories: ["Productivity"],
    installCommand: "openclaw skills install himalaya",
    docsUrl: "https://clawhub.ai/lamelas/himalaya",
    license: "undeclared",
    status: "stable",
    provenance: "indexed",
    featured: false,
    tags: ["clawhub", "openclaw", "productivity"],
    createdAt: "2026-05-29",
    stats: { installs: 1549, stars: 69, fetchedAt: "2026-06-29" },
    source: "clawhub:lamelas/himalaya",
    external: true,
  },
  {
    id: "clawhub-browser-use",
    name: "Browser Use",
    slug: "clawhub-browser-use",
    kind: "listing",
    description: "Automate browser interactions for testing, form filling, screenshots, and data extraction.",
    longDescription:
      "Automate browser interactions for testing, form filling, screenshots, and data extraction. Indexed from ClawHub for discovery; install via OpenClaw. Solid State has not audited this skill.",
    author: "shawnpana",
    version: "2.0.1",
    platforms: ["openclaw", "generic"],
    categories: ["Automation"],
    installCommand: "openclaw skills install browser-use",
    docsUrl: "https://clawhub.ai/shawnpana/browser-use",
    license: "MIT-0",
    status: "stable",
    provenance: "indexed",
    featured: false,
    tags: ["clawhub", "openclaw", "automation"],
    createdAt: "2026-05-29",
    stats: { installs: 474, stars: 109, fetchedAt: "2026-06-29" },
    source: "clawhub:shawnpana/browser-use",
    external: true,
  },
  {
    id: "clawhub-memory-setup",
    name: "Memory Setup",
    slug: "clawhub-memory-setup",
    kind: "listing",
    description: "Enable and configure Clawdbot memory search (MEMORY.md, daily logs, vector search).",
    longDescription:
      "Enable and configure Clawdbot memory search (MEMORY.md, daily logs, vector search). Indexed from ClawHub for discovery; install via OpenClaw. Solid State has not audited this skill.",
    author: "jrbobbyhansen-pixel",
    version: "1.0.0",
    platforms: ["openclaw", "generic"],
    categories: ["AI"],
    installCommand: "openclaw skills install memory-setup",
    docsUrl: "https://clawhub.ai/jrbobbyhansen-pixel/memory-setup",
    license: "undeclared",
    status: "stable",
    provenance: "indexed",
    featured: false,
    tags: ["clawhub", "openclaw", "ai"],
    createdAt: "2026-05-29",
    stats: { installs: 1468, stars: 129, fetchedAt: "2026-06-29" },
    source: "clawhub:jrbobbyhansen-pixel/memory-setup",
    external: true,
  },
]
