// Solid State — Hermes Agent first-party skills, indexed 2026-06-07.
// Source: github.com/NousResearch/hermes-agent (184K★, #1 OpenRouter app).
// License MIT verified against the repo's actual LICENSE file (Copyright (c) 2025
// Nous Research) — not a badge. All skills below live in that repo, so the
// repo-level grant covers them.
//
// Curation (top of the bundled + optional catalogs, safety-filtered):
//   - EXCLUDED red-teaming (godmode) and refusal-removal (obliteratus).
//   - EXCLUDED Hermes-internal plumbing (kanban-*, hermes-*, yuanbao, openclaw-migration).
//   - EXCLUDED vendor-funnel skills (blackbox, inference-sh-cli, parallel-cli).
//   - EXCLUDED humanizer — already indexed via ClawHub (clawhub-humanizer).
//   - provenance "indexed" = listed for discovery, NOT Solid-State-audited.
//   - No per-skill install telemetry exists upstream, so no stats block. Honest > full.
//
// Bundled skills ship with Hermes (`~/.hermes/skills/`); optional ones install via
// `hermes skills install official/<category>/<name>`. All use the agentskills.io
// SKILL.md spec, so they are portable to other spec-compliant runtimes.

import { Skill } from "./types"

const HERMES = "https://hermes-agent.nousresearch.com/docs/user-guide/skills"
const REPO = "https://github.com/NousResearch/hermes-agent/tree/main"

export const hermesListings: Skill[] = [
  // ---- bundled ------------------------------------------------------------
  {
    id: "hermes-youtube-content",
    name: "YouTube Content",
    slug: "hermes-youtube-content",
    kind: "listing",
    description: "YouTube transcripts to summaries, threads, and blog posts.",
    longDescription:
      "Turns YouTube transcripts into summaries, X threads, and blog drafts. Bundled with Hermes Agent (ships pre-installed); portable to other agentskills.io-compliant runtimes. Indexed from the NousResearch/hermes-agent repo for discovery — Solid State has not audited this skill.",
    author: "NousResearch",
    version: "0.0.0",
    platforms: ["hermes", "generic"],
    categories: ["Media", "Writing"],
    repoUrl: `${REPO}/skills/media/youtube-content`,
    docsUrl: `${HERMES}/bundled/media/media-youtube-content`,
    license: "MIT",
    status: "stable",
    provenance: "indexed",
    price: "free",
    featured: false,
    tags: ["hermes", "youtube", "transcripts", "content"],
    createdAt: "2026-06-07",
    source: "NousResearch/hermes-agent",
    external: true,
  },
  {
    id: "hermes-systematic-debugging",
    name: "Systematic Debugging",
    slug: "hermes-systematic-debugging",
    kind: "listing",
    description: "4-phase root-cause debugging: understand bugs before fixing them.",
    longDescription:
      "A 4-phase root-cause debugging discipline — reproduce, isolate, understand, then fix. Bundled with Hermes Agent; portable to other agentskills.io-compliant runtimes. Indexed from the NousResearch/hermes-agent repo for discovery — Solid State has not audited this skill.",
    author: "NousResearch",
    version: "0.0.0",
    platforms: ["hermes", "generic"],
    categories: ["Engineering"],
    repoUrl: `${REPO}/skills/software-development/systematic-debugging`,
    docsUrl: `${HERMES}/bundled/software-development/software-development-systematic-debugging`,
    license: "MIT",
    status: "stable",
    provenance: "indexed",
    price: "free",
    featured: false,
    tags: ["hermes", "debugging", "engineering", "workflow"],
    createdAt: "2026-06-07",
    source: "NousResearch/hermes-agent",
    external: true,
  },
  {
    id: "hermes-test-driven-development",
    name: "Test-Driven Development",
    slug: "hermes-test-driven-development",
    kind: "listing",
    description: "Enforce RED-GREEN-REFACTOR: tests before code, every time.",
    longDescription:
      "Enforces the RED-GREEN-REFACTOR loop — failing test first, minimal pass, then refactor. Bundled with Hermes Agent; portable to other agentskills.io-compliant runtimes. Indexed from the NousResearch/hermes-agent repo for discovery — Solid State has not audited this skill.",
    author: "NousResearch",
    version: "0.0.0",
    platforms: ["hermes", "generic"],
    categories: ["Engineering"],
    repoUrl: `${REPO}/skills/software-development/test-driven-development`,
    docsUrl: `${HERMES}/bundled/software-development/software-development-test-driven-development`,
    license: "MIT",
    status: "stable",
    provenance: "indexed",
    price: "free",
    featured: false,
    tags: ["hermes", "tdd", "testing", "engineering"],
    createdAt: "2026-06-07",
    source: "NousResearch/hermes-agent",
    external: true,
  },
  {
    id: "hermes-excalidraw",
    name: "Excalidraw Diagrams",
    slug: "hermes-excalidraw",
    kind: "listing",
    description: "Hand-drawn-style Excalidraw JSON diagrams: architecture, flow, sequence.",
    longDescription:
      "Generates hand-drawn-style Excalidraw JSON diagrams — architecture, flowcharts, sequence diagrams — ready to open or embed. Bundled with Hermes Agent; portable to other agentskills.io-compliant runtimes. Indexed from the NousResearch/hermes-agent repo for discovery — Solid State has not audited this skill.",
    author: "NousResearch",
    version: "0.0.0",
    platforms: ["hermes", "generic"],
    categories: ["Creative", "Engineering"],
    repoUrl: `${REPO}/skills/creative/excalidraw`,
    docsUrl: `${HERMES}/bundled/creative/creative-excalidraw`,
    license: "MIT",
    status: "stable",
    provenance: "indexed",
    price: "free",
    featured: false,
    tags: ["hermes", "diagrams", "excalidraw", "design"],
    createdAt: "2026-06-07",
    source: "NousResearch/hermes-agent",
    external: true,
  },
  {
    id: "hermes-popular-web-designs",
    name: "Popular Web Designs",
    slug: "hermes-popular-web-designs",
    kind: "listing",
    description: "54 real design systems (Stripe, Linear, Vercel) reproduced as HTML/CSS.",
    longDescription:
      "Reproduces 54 real-world design systems — Stripe, Linear, Vercel and more — as clean HTML/CSS starting points. Bundled with Hermes Agent; portable to other agentskills.io-compliant runtimes. Indexed from the NousResearch/hermes-agent repo for discovery — Solid State has not audited this skill.",
    author: "NousResearch",
    version: "0.0.0",
    platforms: ["hermes", "generic"],
    categories: ["Creative", "Web"],
    repoUrl: `${REPO}/skills/creative/popular-web-designs`,
    docsUrl: `${HERMES}/bundled/creative/creative-popular-web-designs`,
    license: "MIT",
    status: "stable",
    provenance: "indexed",
    price: "free",
    featured: false,
    tags: ["hermes", "design-systems", "html", "css"],
    createdAt: "2026-06-07",
    source: "NousResearch/hermes-agent",
    external: true,
  },
  {
    id: "hermes-manim-video",
    name: "Manim Video",
    slug: "hermes-manim-video",
    kind: "listing",
    description: "Manim CE animations: 3Blue1Brown-style math and algorithm videos.",
    longDescription:
      "Produces 3Blue1Brown-style math and algorithm explainer videos with Manim Community Edition. Bundled with Hermes Agent; portable to other agentskills.io-compliant runtimes. Indexed from the NousResearch/hermes-agent repo for discovery — Solid State has not audited this skill.",
    author: "NousResearch",
    version: "0.0.0",
    platforms: ["hermes", "generic"],
    categories: ["Creative", "Media"],
    repoUrl: `${REPO}/skills/creative/manim-video`,
    docsUrl: `${HERMES}/bundled/creative/creative-manim-video`,
    license: "MIT",
    status: "stable",
    provenance: "indexed",
    price: "free",
    featured: false,
    tags: ["hermes", "manim", "video", "math"],
    createdAt: "2026-06-07",
    source: "NousResearch/hermes-agent",
    external: true,
  },
  {
    id: "hermes-ocr-and-documents",
    name: "OCR & Documents",
    slug: "hermes-ocr-and-documents",
    kind: "listing",
    description: "Extract text from PDFs and scans via pymupdf and marker-pdf.",
    longDescription:
      "Extracts text from PDFs and scanned documents using pymupdf and marker-pdf. Bundled with Hermes Agent; portable to other agentskills.io-compliant runtimes. Indexed from the NousResearch/hermes-agent repo for discovery — Solid State has not audited this skill.",
    author: "NousResearch",
    version: "0.0.0",
    platforms: ["hermes", "generic"],
    categories: ["Productivity", "Documents"],
    repoUrl: `${REPO}/skills/productivity/ocr-and-documents`,
    docsUrl: `${HERMES}/bundled/productivity/productivity-ocr-and-documents`,
    license: "MIT",
    status: "stable",
    provenance: "indexed",
    price: "free",
    featured: false,
    tags: ["hermes", "ocr", "pdf", "documents"],
    createdAt: "2026-06-07",
    source: "NousResearch/hermes-agent",
    external: true,
  },
  {
    id: "hermes-maps",
    name: "Maps",
    slug: "hermes-maps",
    kind: "listing",
    description: "Geocode, POIs, routes, and timezones via OpenStreetMap/OSRM. No API key.",
    longDescription:
      "Geocoding, points of interest, routing, and timezone lookups via OpenStreetMap and OSRM — no API key required. Bundled with Hermes Agent; portable to other agentskills.io-compliant runtimes. Indexed from the NousResearch/hermes-agent repo for discovery — Solid State has not audited this skill.",
    author: "NousResearch",
    version: "0.0.0",
    platforms: ["hermes", "generic"],
    categories: ["Productivity", "Research"],
    repoUrl: `${REPO}/skills/productivity/maps`,
    docsUrl: `${HERMES}/bundled/productivity/productivity-maps`,
    license: "MIT",
    status: "stable",
    provenance: "indexed",
    price: "free",
    featured: false,
    tags: ["hermes", "maps", "geocoding", "openstreetmap"],
    createdAt: "2026-06-07",
    source: "NousResearch/hermes-agent",
    external: true,
  },
  {
    id: "hermes-arxiv",
    name: "arXiv Search",
    slug: "hermes-arxiv",
    kind: "listing",
    description: "Search arXiv papers by keyword, author, category, or ID.",
    longDescription:
      "Searches arXiv by keyword, author, category, or paper ID. Bundled with Hermes Agent; portable to other agentskills.io-compliant runtimes. Indexed from the NousResearch/hermes-agent repo for discovery — Solid State has not audited this skill.",
    author: "NousResearch",
    version: "0.0.0",
    platforms: ["hermes", "generic"],
    categories: ["Research"],
    repoUrl: `${REPO}/skills/research/arxiv`,
    docsUrl: `${HERMES}/bundled/research/research-arxiv`,
    license: "MIT",
    status: "stable",
    provenance: "indexed",
    price: "free",
    featured: false,
    tags: ["hermes", "arxiv", "research", "papers"],
    createdAt: "2026-06-07",
    source: "NousResearch/hermes-agent",
    external: true,
  },
  // ---- optional (hermes skills install official/<category>/<name>) --------
  {
    id: "hermes-duckduckgo-search",
    name: "DuckDuckGo Search",
    slug: "hermes-duckduckgo-search",
    kind: "listing",
    description: "Free web search via DuckDuckGo — text, news, images, videos. No API key.",
    longDescription:
      "Free web search via DuckDuckGo — text, news, images, and videos with no API key. Optional Hermes skill: `hermes skills install official/research/duckduckgo-search`. Portable to other agentskills.io-compliant runtimes. Indexed from the NousResearch/hermes-agent repo for discovery — Solid State has not audited this skill.",
    author: "NousResearch",
    version: "0.0.0",
    platforms: ["hermes", "generic"],
    categories: ["Research"],
    installCommand: "hermes skills install official/research/duckduckgo-search",
    repoUrl: `${REPO}/optional-skills/research/duckduckgo-search`,
    docsUrl: `${HERMES}/optional/research/research-duckduckgo-search`,
    license: "MIT",
    status: "stable",
    provenance: "indexed",
    price: "free",
    featured: false,
    tags: ["hermes", "search", "duckduckgo", "research"],
    createdAt: "2026-06-07",
    source: "NousResearch/hermes-agent",
    external: true,
  },
  {
    id: "hermes-domain-intel",
    name: "Domain Intel",
    slug: "hermes-domain-intel",
    kind: "listing",
    description: "Passive domain recon: subdomains, SSL certs, WHOIS, DNS. Python stdlib only.",
    longDescription:
      "Passive domain reconnaissance with the Python standard library — subdomain discovery, SSL certificate inspection, WHOIS, DNS records, availability checks, bulk analysis. No API keys. Optional Hermes skill: `hermes skills install official/research/domain-intel`. Indexed from the NousResearch/hermes-agent repo for discovery — Solid State has not audited this skill.",
    author: "NousResearch",
    version: "0.0.0",
    platforms: ["hermes", "generic"],
    categories: ["Research", "Security"],
    installCommand: "hermes skills install official/research/domain-intel",
    repoUrl: `${REPO}/optional-skills/research/domain-intel`,
    docsUrl: `${HERMES}/optional/research/research-domain-intel`,
    license: "MIT",
    status: "stable",
    provenance: "indexed",
    price: "free",
    featured: false,
    tags: ["hermes", "domains", "osint", "dns"],
    createdAt: "2026-06-07",
    source: "NousResearch/hermes-agent",
    external: true,
  },
  {
    id: "hermes-oss-forensics",
    name: "OSS Forensics",
    slug: "hermes-oss-forensics",
    kind: "listing",
    description: "Supply-chain forensics for GitHub repos: deleted commits, force-pushes, IOCs.",
    longDescription:
      "Supply-chain investigation for GitHub repositories — deleted-commit recovery, force-push detection, IOC extraction, multi-source evidence collection. Optional Hermes skill: `hermes skills install official/security/oss-forensics`. Indexed from the NousResearch/hermes-agent repo for discovery — Solid State has not audited this skill.",
    author: "NousResearch",
    version: "0.0.0",
    platforms: ["hermes", "generic"],
    categories: ["Security"],
    installCommand: "hermes skills install official/security/oss-forensics",
    repoUrl: `${REPO}/optional-skills/security/oss-forensics`,
    docsUrl: `${HERMES}/optional/security/security-oss-forensics`,
    license: "MIT",
    status: "stable",
    provenance: "indexed",
    price: "free",
    featured: false,
    tags: ["hermes", "security", "supply-chain", "forensics"],
    createdAt: "2026-06-07",
    source: "NousResearch/hermes-agent",
    external: true,
  },
  {
    id: "hermes-fastmcp",
    name: "FastMCP Builder",
    slug: "hermes-fastmcp",
    kind: "listing",
    description: "Build, test, and deploy MCP servers with FastMCP in Python.",
    longDescription:
      "Build, test, inspect, install, and deploy MCP servers with FastMCP in Python — wrap any API or database as MCP tools. Optional Hermes skill: `hermes skills install official/mcp/fastmcp`. Indexed from the NousResearch/hermes-agent repo for discovery — Solid State has not audited this skill.",
    author: "NousResearch",
    version: "0.0.0",
    platforms: ["hermes", "generic"],
    categories: ["Engineering", "MCP"],
    installCommand: "hermes skills install official/mcp/fastmcp",
    repoUrl: `${REPO}/optional-skills/mcp/fastmcp`,
    docsUrl: `${HERMES}/optional/mcp/mcp-fastmcp`,
    license: "MIT",
    status: "stable",
    provenance: "indexed",
    price: "free",
    featured: false,
    tags: ["hermes", "mcp", "fastmcp", "python"],
    createdAt: "2026-06-07",
    source: "NousResearch/hermes-agent",
    external: true,
  },
  {
    id: "hermes-meme-generation",
    name: "Meme Generation",
    slug: "hermes-meme-generation",
    kind: "listing",
    description: "Generate real meme PNGs: pick a template, overlay text with Pillow.",
    longDescription:
      "Generates actual .png meme files — picks a template and overlays text with Pillow. Optional Hermes skill: `hermes skills install official/creative/meme-generation`. Indexed from the NousResearch/hermes-agent repo for discovery — Solid State has not audited this skill.",
    author: "NousResearch",
    version: "0.0.0",
    platforms: ["hermes", "generic"],
    categories: ["Creative", "Media"],
    installCommand: "hermes skills install official/creative/meme-generation",
    repoUrl: `${REPO}/optional-skills/creative/meme-generation`,
    docsUrl: `${HERMES}/optional/creative/creative-meme-generation`,
    license: "MIT",
    status: "stable",
    provenance: "indexed",
    price: "free",
    featured: false,
    tags: ["hermes", "memes", "images", "creative"],
    createdAt: "2026-06-07",
    source: "NousResearch/hermes-agent",
    external: true,
  },
  {
    id: "hermes-solana",
    name: "Solana Query",
    slug: "hermes-solana",
    kind: "listing",
    description: "Query Solana chain data with USD pricing: wallets, tokens, NFTs, whales. No API key.",
    longDescription:
      "Queries Solana blockchain data with USD pricing — wallet balances, token portfolios, transaction details, NFTs, whale detection, live network stats. Uses Solana RPC + CoinGecko, no API key. Read-only: it queries chain data, it does not move funds. Optional Hermes skill: `hermes skills install official/blockchain/solana`. Indexed from the NousResearch/hermes-agent repo for discovery — Solid State has not audited this skill.",
    author: "NousResearch",
    version: "0.0.0",
    platforms: ["hermes", "generic"],
    categories: ["Crypto", "Research"],
    installCommand: "hermes skills install official/blockchain/solana",
    repoUrl: `${REPO}/optional-skills/blockchain/solana`,
    docsUrl: `${HERMES}/optional/blockchain/blockchain-solana`,
    license: "MIT",
    status: "stable",
    provenance: "indexed",
    price: "free",
    featured: false,
    tags: ["hermes", "solana", "crypto", "onchain"],
    createdAt: "2026-06-07",
    source: "NousResearch/hermes-agent",
    external: true,
  },
]
