// Solid State — official vendor MCP servers
//
// MCP servers are the connector layer: they let an agent operate the
// software a business already runs. This file indexes OFFICIAL,
// vendor-published servers only. No community forks, no wrappers.
//
// Honesty rules (same as the rest of the directory):
//   - Every endpoint, repo, and license verified against vendor docs,
//     the GitHub API, or the npm registry on 2026-06-07.
//   - No install counts. None of these vendors publish telemetry we trust.
//   - "proprietary" = hosted closed-source server. "source-available" =
//     public source under a non-OSS license (e.g. Sentry's FSL).
//   - installCommand carries the remote endpoint URL when the server is
//     remote-only — that IS the install string for an MCP client.

import { Skill } from "./types"

export const mcpServers: Skill[] = [
  {
    id: "mcp-github",
    name: "GitHub MCP Server",
    slug: "mcp-github",
    kind: "listing",
    description:
      "GitHub's official MCP server. Repos, issues, PRs, Actions, code security — the full platform as agent tools.",
    longDescription:
      "Official remote MCP server from GitHub, hosted at https://api.githubcopilot.com/mcp/ (Streamable HTTP). Exposes repositories, issues, pull requests, Actions, and code security as tools. OAuth on the remote endpoint; PAT supported. Also runs locally as a Go binary or Docker image. Indexed for discovery — Solid State has not audited this server.",
    author: "github",
    version: "see upstream",
    platforms: ["generic"],
    categories: ["MCP", "Engineering"],
    installCommand: "https://api.githubcopilot.com/mcp/",
    repoUrl: "https://github.com/github/github-mcp-server",
    docsUrl:
      "https://docs.github.com/en/copilot/how-tos/provide-context/use-mcp-in-your-ide/set-up-the-github-mcp-server",
    license: "MIT",
    status: "stable",
    provenance: "indexed",
    price: "free",
    featured: false,
    tags: ["mcp", "connector", "github", "remote"],
    createdAt: "2026-06-07",
  },
  {
    id: "mcp-slack",
    name: "Slack MCP Server",
    slug: "mcp-slack",
    kind: "listing",
    description:
      "Slack's official MCP server. Search channels and messages, send messages, work with canvases.",
    longDescription:
      "Official hosted MCP server from Slack at https://mcp.slack.com/mcp. Search channels and message history, send messages, manage canvases and users. OAuth with workspace-admin approval; restricted to Marketplace-listed and internal apps. Launched February 2026. Indexed for discovery — Solid State has not audited this server.",
    author: "slack",
    version: "see upstream",
    platforms: ["generic"],
    categories: ["MCP", "Productivity"],
    installCommand: "https://mcp.slack.com/mcp",
    docsUrl: "https://docs.slack.dev/ai/slack-mcp-server/",
    license: "proprietary",
    status: "stable",
    provenance: "indexed",
    price: "free",
    featured: false,
    tags: ["mcp", "connector", "slack", "remote"],
    createdAt: "2026-06-07",
  },
  {
    id: "mcp-notion",
    name: "Notion MCP",
    slug: "mcp-notion",
    kind: "listing",
    description:
      "Notion's official MCP server. Search, read, create, and update pages and databases.",
    longDescription:
      "Official MCP server from Notion. Remote at https://mcp.notion.com/mcp with OAuth, or local via the open-source @notionhq/notion-mcp-server package (MIT) with an API token. Upstream notes the local server may be sunset in favor of the remote. Indexed for discovery — Solid State has not audited this server.",
    author: "makenotion",
    version: "see upstream",
    platforms: ["generic"],
    categories: ["MCP", "Productivity"],
    installCommand: "npx -y @notionhq/notion-mcp-server",
    repoUrl: "https://github.com/makenotion/notion-mcp-server",
    docsUrl: "https://developers.notion.com/guides/mcp/overview",
    license: "MIT",
    status: "stable",
    provenance: "indexed",
    price: "free",
    featured: false,
    tags: ["mcp", "connector", "notion", "remote"],
    createdAt: "2026-06-07",
  },
  {
    id: "mcp-stripe",
    name: "Stripe MCP",
    slug: "mcp-stripe",
    kind: "listing",
    description:
      "Stripe's official MCP server. Customers, payments, invoices, subscriptions, plus doc search.",
    longDescription:
      "Official MCP server from Stripe. Remote at https://mcp.stripe.com with OAuth, or local via the open-source @stripe/mcp package (MIT) with an API key. Exposes Stripe API actions — customers, payments, invoices, subscriptions — and knowledge-base search. Indexed for discovery — Solid State has not audited this server.",
    author: "stripe",
    version: "see upstream",
    platforms: ["generic"],
    categories: ["MCP", "Payments"],
    installCommand: "npx -y @stripe/mcp --tools=all",
    repoUrl: "https://github.com/stripe/ai",
    docsUrl: "https://docs.stripe.com/mcp",
    license: "MIT",
    status: "stable",
    provenance: "indexed",
    price: "free",
    featured: false,
    tags: ["mcp", "connector", "stripe", "payments", "remote"],
    createdAt: "2026-06-07",
  },
  {
    id: "mcp-supabase",
    name: "Supabase MCP",
    slug: "mcp-supabase",
    kind: "listing",
    description:
      "Supabase's official MCP server. Run SQL, manage projects and branches, deploy edge functions.",
    longDescription:
      "Official MCP server from Supabase. Remote at https://mcp.supabase.com/mcp (supports ?project_ref=, ?read_only=true, ?features= params), or local stdio from the same Apache-2.0 repo. Manage projects and branches, run SQL, apply migrations, deploy edge functions, read logs and advisors. OAuth 2 by default; PAT supported. Indexed for discovery — Solid State has not audited this server.",
    author: "supabase",
    version: "see upstream",
    platforms: ["generic"],
    categories: ["MCP", "Data"],
    installCommand: "https://mcp.supabase.com/mcp",
    repoUrl: "https://github.com/supabase/mcp",
    docsUrl: "https://supabase.com/docs/guides/getting-started/mcp",
    license: "Apache-2.0",
    status: "stable",
    provenance: "indexed",
    price: "free",
    featured: false,
    tags: ["mcp", "connector", "supabase", "database", "remote"],
    createdAt: "2026-06-07",
  },
  {
    id: "mcp-vercel",
    name: "Vercel MCP",
    slug: "mcp-vercel",
    kind: "listing",
    description:
      "Vercel's official MCP server. Manage projects and deployments, analyze logs, search docs.",
    longDescription:
      "Official hosted MCP server from Vercel at https://mcp.vercel.com. Docs search plus team, project, and deployment management and deployment-log analysis. OAuth per the MCP Authorization spec, with an approved-client allowlist. Indexed for discovery — Solid State has not audited this server.",
    author: "vercel",
    version: "see upstream",
    platforms: ["generic"],
    categories: ["MCP", "DevOps"],
    installCommand: "https://mcp.vercel.com",
    docsUrl: "https://vercel.com/docs/agent-resources/vercel-mcp",
    license: "proprietary",
    status: "stable",
    provenance: "indexed",
    price: "free",
    featured: false,
    tags: ["mcp", "connector", "vercel", "deployment", "remote"],
    createdAt: "2026-06-07",
  },
  {
    id: "mcp-figma",
    name: "Figma MCP Server",
    slug: "mcp-figma",
    kind: "listing",
    description:
      "Figma's official MCP server. Design context for code generation, variables, components, FigJam.",
    longDescription:
      "Official MCP server from Figma. Remote at https://mcp.figma.com/mcp, plus a desktop-app local server in Dev Mode. Extracts design context for code generation, reads variables and components, writes to canvas (beta), and builds FigJam diagrams. OAuth with a client allowlist via the Figma MCP Catalog. Indexed for discovery — Solid State has not audited this server.",
    author: "figma",
    version: "see upstream",
    platforms: ["generic"],
    categories: ["MCP", "Design & UI"],
    installCommand: "https://mcp.figma.com/mcp",
    docsUrl: "https://developers.figma.com/docs/figma-mcp-server/",
    license: "proprietary",
    status: "stable",
    provenance: "indexed",
    price: "free",
    featured: false,
    tags: ["mcp", "connector", "figma", "design", "remote"],
    createdAt: "2026-06-07",
  },
  {
    id: "mcp-linear",
    name: "Linear MCP",
    slug: "mcp-linear",
    kind: "listing",
    description:
      "Linear's official MCP server. Find, create, and update issues, projects, and comments.",
    longDescription:
      "Official hosted MCP server from Linear at https://mcp.linear.app/mcp (Streamable HTTP). Find, create, and update issues, projects, and comments. OAuth 2.1 with dynamic client registration; API-key bearer header also supported. Non-remote clients can bridge via npx -y mcp-remote. Indexed for discovery — Solid State has not audited this server.",
    author: "linear",
    version: "see upstream",
    platforms: ["generic"],
    categories: ["MCP", "Productivity"],
    installCommand: "https://mcp.linear.app/mcp",
    docsUrl: "https://linear.app/docs/mcp",
    license: "proprietary",
    status: "stable",
    provenance: "indexed",
    price: "free",
    featured: false,
    tags: ["mcp", "connector", "linear", "issues", "remote"],
    createdAt: "2026-06-07",
  },
  {
    id: "mcp-sentry",
    name: "Sentry MCP",
    slug: "mcp-sentry",
    kind: "listing",
    description:
      "Sentry's official MCP server. Query issues, errors, and projects; run Seer AI analysis.",
    longDescription:
      "Official MCP server from Sentry. Remote at https://mcp.sentry.dev with OAuth, or local stdio via @sentry/mcp-server with an access token. Queries issues, errors, projects, and DSNs, and triggers Seer AI analysis. License is FSL-1.1-Apache-2.0 — source-available, converts to Apache-2.0 after two years, not plain open source. Indexed for discovery — Solid State has not audited this server.",
    author: "getsentry",
    version: "see upstream",
    platforms: ["generic"],
    categories: ["MCP", "DevOps"],
    installCommand: "https://mcp.sentry.dev",
    repoUrl: "https://github.com/getsentry/sentry-mcp",
    docsUrl: "https://docs.sentry.io/product/sentry-mcp/",
    license: "source-available",
    status: "stable",
    provenance: "indexed",
    price: "free",
    featured: false,
    tags: ["mcp", "connector", "sentry", "monitoring", "remote"],
    createdAt: "2026-06-07",
  },
  {
    id: "mcp-cloudflare",
    name: "Cloudflare MCP Servers",
    slug: "mcp-cloudflare",
    kind: "listing",
    description:
      "Cloudflare's official MCP servers. Full API via Code Mode, plus 15+ domain servers (docs, logs, DNS, Radar…).",
    longDescription:
      "Official MCP server family from Cloudflare. Code Mode API server at https://mcp.cloudflare.com/mcp exposes the full API via search()/execute(); 15+ domain servers live at *.mcp.cloudflare.com/mcp (docs, observability, bindings, radar, browser rendering, DNS analytics, logs, and more — /sse endpoints deprecated). OAuth; the docs server needs no auth. Apache-2.0. Indexed for discovery — Solid State has not audited these servers.",
    author: "cloudflare",
    version: "see upstream",
    platforms: ["generic"],
    categories: ["MCP", "DevOps"],
    installCommand: "https://mcp.cloudflare.com/mcp",
    repoUrl: "https://github.com/cloudflare/mcp",
    docsUrl:
      "https://developers.cloudflare.com/agents/model-context-protocol/mcp-servers-for-cloudflare/",
    license: "Apache-2.0",
    status: "stable",
    provenance: "indexed",
    price: "free",
    featured: false,
    tags: ["mcp", "connector", "cloudflare", "infrastructure", "remote"],
    createdAt: "2026-06-07",
  },
  {
    id: "mcp-atlassian",
    name: "Atlassian Rovo MCP Server",
    slug: "mcp-atlassian",
    kind: "listing",
    description:
      "Atlassian's official MCP server. Jira issues, Confluence pages, Compass components — permissions intact.",
    longDescription:
      "Official remote MCP server from Atlassian at https://mcp.atlassian.com/v1/mcp/authv2 (the old /v1/sse endpoint is unsupported after June 30, 2026). Search, summarize, create, and update Jira issues, Confluence pages, and Compass components, respecting existing permissions. OAuth 2.1. GA since February 2026. Indexed for discovery — Solid State has not audited this server.",
    author: "atlassian",
    version: "see upstream",
    platforms: ["generic"],
    categories: ["MCP", "Productivity"],
    installCommand: "https://mcp.atlassian.com/v1/mcp/authv2",
    repoUrl: "https://github.com/atlassian/atlassian-mcp-server",
    docsUrl:
      "https://support.atlassian.com/atlassian-rovo-mcp-server/docs/getting-started-with-the-atlassian-remote-mcp-server/",
    license: "Apache-2.0",
    status: "stable",
    provenance: "indexed",
    price: "free",
    featured: false,
    tags: ["mcp", "connector", "atlassian", "jira", "confluence", "remote"],
    createdAt: "2026-06-07",
  },
  {
    id: "mcp-asana",
    name: "Asana MCP Server",
    slug: "mcp-asana",
    kind: "listing",
    description:
      "Asana's official MCP server. Create tasks, search projects, analyze workload in the Work Graph.",
    longDescription:
      "Official hosted MCP server from Asana at https://mcp.asana.com/v2/mcp (V2 — the V1 SSE endpoint shuts down May 11, 2026). Create tasks, search projects, and analyze workload in the Asana Work Graph. OAuth 2.0 with a registered client. Indexed for discovery — Solid State has not audited this server.",
    author: "asana",
    version: "see upstream",
    platforms: ["generic"],
    categories: ["MCP", "Productivity"],
    installCommand: "https://mcp.asana.com/v2/mcp",
    docsUrl: "https://developers.asana.com/docs/mcp-server",
    license: "proprietary",
    status: "stable",
    provenance: "indexed",
    price: "free",
    featured: false,
    tags: ["mcp", "connector", "asana", "tasks", "remote"],
    createdAt: "2026-06-07",
  },
  {
    id: "mcp-paypal",
    name: "PayPal MCP",
    slug: "mcp-paypal",
    kind: "listing",
    description:
      "PayPal's official MCP server. Invoices, payments, disputes, subscriptions — merchant tasks as tools.",
    longDescription:
      "Official MCP server from PayPal. Remote at https://mcp.paypal.com/http (Streamable HTTP; /sse also live, sandbox at mcp.sandbox.paypal.com), or local via @paypal/mcp with an access token. Invoices, payments, disputes, subscriptions, and catalog management. Apache-2.0 agent toolkit. Indexed for discovery — Solid State has not audited this server.",
    author: "paypal",
    version: "see upstream",
    platforms: ["generic"],
    categories: ["MCP", "Payments"],
    installCommand: "npx -y @paypal/mcp --tools=all",
    repoUrl: "https://github.com/paypal/agent-toolkit",
    docsUrl: "https://docs.paypal.ai/developer/tools/ai/mcp-quickstart",
    license: "Apache-2.0",
    status: "stable",
    provenance: "indexed",
    price: "free",
    featured: false,
    tags: ["mcp", "connector", "paypal", "payments", "remote"],
    createdAt: "2026-06-07",
  },
  {
    id: "mcp-shopify-dev",
    name: "Shopify Dev MCP",
    slug: "mcp-shopify-dev",
    kind: "listing",
    description:
      "Shopify's official dev MCP server. Search docs, introspect GraphQL schemas, validate code and themes.",
    longDescription:
      "Official local MCP server from Shopify via @shopify/dev-mcp (ISC per npm). Searches Shopify docs, introspects GraphQL Admin/Storefront schemas, and validates code and themes. No auth required. Shopify also publishes per-store Storefront and Customer Accounts MCP servers for shopping agents — see the Shopify docs. Indexed for discovery — Solid State has not audited this server.",
    author: "shopify",
    version: "see upstream",
    platforms: ["generic"],
    categories: ["MCP", "Engineering"],
    installCommand: "npx -y @shopify/dev-mcp@latest",
    docsUrl: "https://shopify.dev/docs/apps/build/devmcp",
    license: "ISC",
    status: "stable",
    provenance: "indexed",
    price: "free",
    featured: false,
    tags: ["mcp", "connector", "shopify", "commerce"],
    createdAt: "2026-06-07",
  },
  {
    id: "mcp-huggingface",
    name: "Hugging Face MCP Server",
    slug: "mcp-huggingface",
    kind: "listing",
    description:
      "Hugging Face's official MCP server. Search models, datasets, Spaces, and papers; run HF Jobs.",
    longDescription:
      "Official MCP server from Hugging Face at https://huggingface.co/mcp. Model, dataset, Space, and paper search, semantic doc search, HF Jobs, and calling community Gradio Spaces as tools. Configure per-account at huggingface.co/settings/mcp with an HF token. MIT source. Indexed for discovery — Solid State has not audited this server.",
    author: "huggingface",
    version: "see upstream",
    platforms: ["generic"],
    categories: ["MCP", "AI"],
    installCommand: "https://huggingface.co/mcp",
    repoUrl: "https://github.com/huggingface/hf-mcp-server",
    docsUrl: "https://huggingface.co/docs/hub/agents-mcp",
    license: "MIT",
    status: "stable",
    provenance: "indexed",
    price: "free",
    featured: false,
    tags: ["mcp", "connector", "huggingface", "models", "remote"],
    createdAt: "2026-06-07",
  },
  {
    id: "mcp-canva",
    name: "Canva MCP Server",
    slug: "mcp-canva",
    kind: "listing",
    description:
      "Canva's official MCP server. Generate and edit designs, manage assets and brand, export to PDF/PNG/MP4.",
    longDescription:
      "Official hosted MCP server from Canva at https://mcp.canva.com/mcp. Design generation and editing, search, asset and brand management, comments, and export to PDF, PNG, PPTX, and MP4. OAuth with dynamic client registration; new integrator access is waitlist-gated. A separate Canva Dev MCP serves app developers. Indexed for discovery — Solid State has not audited this server.",
    author: "canva",
    version: "see upstream",
    platforms: ["generic"],
    categories: ["MCP", "Design & UI"],
    installCommand: "https://mcp.canva.com/mcp",
    docsUrl: "https://www.canva.dev/docs/mcp/",
    license: "proprietary",
    status: "stable",
    provenance: "indexed",
    price: "free",
    featured: false,
    tags: ["mcp", "connector", "canva", "design", "remote"],
    createdAt: "2026-06-07",
  },
  {
    id: "mcp-zapier",
    name: "Zapier MCP",
    slug: "mcp-zapier",
    kind: "listing",
    description:
      "Zapier's official MCP bridge. One server, 8,000+ apps and 30,000+ actions behind it.",
    longDescription:
      "Official hosted MCP service from Zapier. Each account generates its own server URL at mcp.zapier.com — there is no single public endpoint; the URL acts as the credential. Bridges to 8,000+ apps and 30,000+ actions via user-configured tools. Usage-metered with paid tiers. Indexed for discovery — Solid State has not audited this server.",
    author: "zapier",
    version: "see upstream",
    platforms: ["generic"],
    categories: ["MCP", "Automation"],
    installCommand: "https://mcp.zapier.com",
    repoUrl: "https://github.com/zapier/zapier-mcp",
    docsUrl: "https://docs.zapier.com/mcp/home",
    license: "proprietary",
    status: "stable",
    provenance: "indexed",
    price: "free",
    featured: false,
    tags: ["mcp", "connector", "zapier", "automation", "remote"],
    createdAt: "2026-06-07",
  },
  {
    id: "mcp-square",
    name: "Square MCP Server",
    slug: "mcp-square",
    kind: "listing",
    description:
      "Square's official MCP server. Payments, catalog, customers, bookings, inventory via meta-tools.",
    longDescription:
      "Official MCP server from Square (Block) at https://mcp.squareup.com/sse, with a sandbox-capable local instance from the Apache-2.0 repo. Meta-tools (get_service_info, get_type_info, make_api_request) cover payments, catalog, customers, bookings, and inventory. OAuth with granular scopes. Vendor-labeled Beta. Indexed for discovery — Solid State has not audited this server.",
    author: "square",
    version: "see upstream",
    platforms: ["generic"],
    categories: ["MCP", "Payments"],
    installCommand: "https://mcp.squareup.com/sse",
    repoUrl: "https://github.com/square/square-mcp-server",
    docsUrl: "https://developer.squareup.com/docs/mcp",
    license: "Apache-2.0",
    status: "beta",
    provenance: "indexed",
    price: "free",
    featured: false,
    tags: ["mcp", "connector", "square", "payments", "remote"],
    createdAt: "2026-06-07",
  },
  {
    id: "mcp-intercom",
    name: "Intercom MCP",
    slug: "mcp-intercom",
    kind: "listing",
    description:
      "Intercom's official MCP server. Search conversations and contacts with a query DSL.",
    longDescription:
      "Official hosted MCP server from Intercom at https://mcp.intercom.com/mcp (Streamable HTTP; /sse deprecated). Around six tools for searching conversations and contacts via a query DSL. OAuth recommended; bearer token supported. US-hosted workspaces only — EU and AU are unsupported. Indexed for discovery — Solid State has not audited this server.",
    author: "intercom",
    version: "see upstream",
    platforms: ["generic"],
    categories: ["MCP", "Support"],
    installCommand: "https://mcp.intercom.com/mcp",
    docsUrl: "https://developers.intercom.com/docs/guides/mcp",
    license: "proprietary",
    status: "stable",
    provenance: "indexed",
    price: "free",
    featured: false,
    tags: ["mcp", "connector", "intercom", "support", "remote"],
    createdAt: "2026-06-07",
  },
  {
    id: "mcp-netlify",
    name: "Netlify MCP Server",
    slug: "mcp-netlify",
    kind: "listing",
    description:
      "Netlify's official MCP server. Create, deploy, and manage projects from an agent.",
    longDescription:
      "Official local MCP server from Netlify via @netlify/mcp (ISC per npm). Create, deploy, and manage projects, access controls, extensions, and env vars through the Netlify API and CLI. Auth via Netlify CLI login or a PAT env var. No official remote endpoint is documented. Indexed for discovery — Solid State has not audited this server.",
    author: "netlify",
    version: "see upstream",
    platforms: ["generic"],
    categories: ["MCP", "DevOps"],
    installCommand: "npx -y @netlify/mcp",
    repoUrl: "https://github.com/netlify/netlify-mcp",
    docsUrl: "https://docs.netlify.com/build/build-with-ai/netlify-mcp-server/",
    license: "ISC",
    status: "stable",
    provenance: "indexed",
    price: "free",
    featured: false,
    tags: ["mcp", "connector", "netlify", "deployment"],
    createdAt: "2026-06-07",
  },
  {
    id: "mcp-neon",
    name: "Neon MCP Server",
    slug: "mcp-neon",
    kind: "listing",
    description:
      "Neon's official MCP server. Run SQL, manage branches, do branch-based safe migrations on serverless Postgres.",
    longDescription:
      "Official MCP server from Neon (Databricks). Remote at https://mcp.neon.tech/mcp with OAuth or API key, or local via @neondatabase/mcp-server-neon (MIT). Projects and branches, SQL execution, branch-based safe migrations, query tuning, and Neon Auth provisioning. Neon's own docs scope it to development and testing, not production. Indexed for discovery — Solid State has not audited this server.",
    author: "neondatabase",
    version: "see upstream",
    platforms: ["generic"],
    categories: ["MCP", "Data"],
    installCommand: "https://mcp.neon.tech/mcp",
    repoUrl: "https://github.com/neondatabase/mcp-server-neon",
    docsUrl: "https://neon.com/docs/ai/neon-mcp-server",
    license: "MIT",
    status: "stable",
    provenance: "indexed",
    price: "free",
    featured: false,
    tags: ["mcp", "connector", "neon", "postgres", "database", "remote"],
    createdAt: "2026-06-07",
  },
  {
    id: "mcp-hubspot",
    name: "HubSpot MCP",
    slug: "mcp-hubspot",
    kind: "listing",
    description:
      "HubSpot's official MCP server. Read CRM contacts, companies, deals, tickets, and invoices.",
    longDescription:
      "Official MCP server from HubSpot at mcp.hubspot.com — read-only CRM access to contacts, companies, deals, tickets, and invoices. A separate local Developer MCP ships via the HubSpot CLI (hs mcp setup) for app and CMS scaffolding. OAuth 2.0, with an OAuth 2.1 + PKCE migration announced. GA. Indexed for discovery — Solid State has not audited this server.",
    author: "hubspot",
    version: "see upstream",
    platforms: ["generic"],
    categories: ["MCP", "CRM"],
    installCommand: "https://mcp.hubspot.com",
    docsUrl: "https://developers.hubspot.com/mcp",
    license: "proprietary",
    status: "stable",
    provenance: "indexed",
    price: "free",
    featured: false,
    tags: ["mcp", "connector", "hubspot", "crm", "remote"],
    createdAt: "2026-06-07",
  },
  {
    id: "mcp-x",
    name: "X MCP",
    slug: "mcp-x",
    kind: "listing",
    description:
      "X's official MCP server. Full-archive post search, users, trends, bookmarks, and Articles — as agent tools.",
    longDescription:
      "Official hosted MCP server from X at https://api.x.com/mcp (Streamable HTTP, protocol 2025-06-18). Full-archive post search, user lookup, timelines and mentions, likers and reposters, news and trends by WOEID, bookmark management, and draft/publish Articles — acting with your own account's scopes. Connect through the open-source `xurl mcp` bridge, which owns the OAuth login and refreshes the token. Requires your own X developer app, and the X API is billed pay-per-use — there is no free tier since February 2026 (reads ~$0.005 each, posts created $0.015, or $0.20 with a link). A separate read-only Docs MCP is also listed. Indexed for discovery — Solid State has not audited this server.",
    author: "xdevplatform",
    version: "see upstream",
    platforms: ["generic"],
    categories: ["MCP", "Social"],
    installCommand: "https://api.x.com/mcp",
    repoUrl: "https://github.com/xdevplatform/xmcp",
    docsUrl: "https://docs.x.com/tools/mcp",
    license: "proprietary",
    status: "stable",
    provenance: "indexed",
    price: "free",
    featured: false,
    tags: ["mcp", "connector", "x", "twitter", "social", "remote"],
    createdAt: "2026-06-30",
  },
  {
    id: "mcp-x-docs",
    name: "X Docs MCP",
    slug: "mcp-x-docs",
    kind: "listing",
    description:
      "X's API docs as an MCP. Search and read the X developer documentation from your client.",
    longDescription:
      "Official read-only documentation MCP from X at https://docs.x.com/mcp. Two tools: search_x to search the X API docs, and get_page_x to fetch a doc page by path. Remote, no authentication, no cost. Pairs with the X MCP so an agent can look up endpoint details while it builds. Indexed for discovery — Solid State has not audited this server.",
    author: "xdevplatform",
    version: "see upstream",
    platforms: ["generic"],
    categories: ["MCP", "Engineering"],
    installCommand: "https://docs.x.com/mcp",
    docsUrl: "https://docs.x.com/tools/mcp",
    license: "proprietary",
    status: "stable",
    provenance: "indexed",
    price: "free",
    featured: false,
    tags: ["mcp", "connector", "x", "twitter", "docs", "remote"],
    createdAt: "2026-06-30",
  },
]
