// AUTO-GENERATED by scripts/refresh-models.mjs — do not edit by hand.
// Source: https://models.dev/api.json (open data, github.com/anomalyco/models.dev).
// Captured 2026-06-08.
export const MODELS_META = {
  captured: "2026-06-08",
  models: 5042,
  providers: 140,
}
