// AUTO-GENERATED by scripts/refresh-models.mjs — do not edit by hand.
// Source: https://models.dev/catalog.json (open data, github.com/sst/models.dev).
// Captured 2026-06-10.
export const MODELS_META = {
  captured: "2026-06-10",
  models: 210,
  providers: 140,
  labs: 17,
}
