// AUTO-GENERATED by scripts/refresh-models.mjs — do not edit by hand.
// Source: https://models.dev/catalog.json (open data, github.com/sst/models.dev).
// Captured 2026-06-15.
export const MODELS_META = {
  captured: "2026-06-15",
  models: 216,
  providers: 145,
  labs: 18,
}
