// Regenerate the models index from https://models.dev/api.json.
//
// models.dev is the open-source model database by the Anomaly/SST team
// (github.com/anomalyco/models.dev). We flatten provider→models into rows,
// keep only the fields the /models page renders, and write:
//   public/data/models.json  — the row data (fetched client-side)
//   lib/modelsMeta.ts        — counts + capture date for the page header
//
// Usage:  node scripts/refresh-models.mjs
//         node scripts/refresh-models.mjs --dry
//
// Run weekly via the Cowork scheduled task "solidstate-models-sync".
// The script never pushes — Thor commits.

import { writeFileSync, mkdirSync } from "node:fs"

const API = "https://models.dev/api.json"
const DRY = process.argv.includes("--dry")
const OUT_JSON = new URL("../public/data/models.json", import.meta.url)
const OUT_META = new URL("../lib/modelsMeta.ts", import.meta.url)

const res = await fetch(API)
if (!res.ok) {
  console.error(`models.dev fetch failed: ${res.status}`)
  process.exit(1)
}
const db = await res.json()

const rows = []
for (const provider of Object.values(db)) {
  const providerId = provider.id
  const providerName = provider.name ?? provider.id
  for (const m of Object.values(provider.models ?? {})) {
    if (m.status === "retired" || m.status === "deprecated") continue
    rows.push({
      provider: providerId,
      providerName,
      id: m.id,
      name: m.name ?? m.id,
      family: m.family ?? null,
      reasoning: !!m.reasoning,
      toolCall: !!m.tool_call,
      attachment: !!m.attachment,
      openWeights: !!m.open_weights,
      context: m.limit?.context ?? null,
      maxOutput: m.limit?.output ?? null,
      costIn: m.cost?.input ?? null,
      costOut: m.cost?.output ?? null,
      released: m.release_date ?? null,
      updated: m.last_updated ?? null,
      knowledge: m.knowledge ?? null,
      modIn: m.modalities?.input ?? ["text"],
      modOut: m.modalities?.output ?? ["text"],
    })
  }
}

// Sanity guard — if the feed shrinks dramatically, the format probably changed.
if (rows.length < 2000) {
  console.error(`Only ${rows.length} models parsed — feed format probably changed. Aborting, nothing written.`)
  process.exit(1)
}

// Newest first by release date (unknown dates last).
rows.sort((a, b) => String(b.released ?? "").localeCompare(String(a.released ?? "")))

const providers = [...new Set(rows.map((r) => r.providerName))].sort((a, b) =>
  a.localeCompare(b)
)
const today = new Date().toISOString().slice(0, 10)

const meta = `// AUTO-GENERATED by scripts/refresh-models.mjs — do not edit by hand.
// Source: https://models.dev/api.json (open data, github.com/anomalyco/models.dev).
// Captured ${today}.
export const MODELS_META = {
  captured: ${JSON.stringify(today)},
  models: ${rows.length},
  providers: ${providers.length},
}
`

if (DRY) {
  console.log(`[dry] ${rows.length} models across ${providers.length} providers (captured ${today})`)
  process.exit(0)
}

mkdirSync(new URL("../public/data/", import.meta.url), { recursive: true })
writeFileSync(OUT_JSON, JSON.stringify({ captured: today, providers, rows }))
writeFileSync(OUT_META, meta)
console.log(`Wrote ${rows.length} models / ${providers.length} providers → public/data/models.json + lib/modelsMeta.ts`)
